const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const mod=()=>import('../../supabase/functions/credit-studio/handler.mjs');
const uid='11111111-1111-4111-8111-111111111111',rid='22222222-2222-4222-8222-222222222222';
function database(options={}){const calls=[];const db={calls,auth:{getUser:async token=>({data:{user:token==='valid'?{id:uid}:null},error:token==='valid'?null:Error()})},from(table){const filters={};const b={select(){return b;},eq(k,v){filters[k]=v;return b;},single:async()=>({data:{environment:'PRODUCTION',model:'gpt-image-2.5-sunburst',sales_enabled:true,renders_enabled:true,costs_verified:true,...options.config},error:null}),maybeSingle:async()=>{calls.push({table,filters});return{data:table==='chisel_credit_accounts'?{balance:7}:null,error:null};}};return b;},rpc:async(name,args)=>{calls.push({name,args});return{data:name==='chisel_credit_reserve'?{error:'insufficient_credits'}:0,error:null};}};return db;}
const req=(body,headers={})=>new Request('https://test.invalid',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer valid',...headers},body:JSON.stringify(body)});
test('wallet is authenticated, no API secret is returned, and missing key disables checkout',async()=>{const{createHandler}=await mod();const db=database();const handler=createHandler({db});let r=await handler(new Request('https://test.invalid'));let b=await r.json();assert.equal(b.wallet,null);assert.equal(b.ready,false);assert.equal(b.salesReady,false);r=await handler(new Request('https://test.invalid',{headers:{authorization:'Bearer valid'}}));b=await r.json();assert.equal(b.wallet.userId,uid);assert.equal(b.wallet.balance,7);assert.ok(!('key' in b));});
test('a device ID or caller-supplied user ID cannot authorize a render',async()=>{const{createHandler}=await mod();const db=database();const handler=createHandler({db,key:'fake-secret'});const r=await handler(req({action:'create',requestId:rid,deviceId:'stolen',userId:uid},{authorization:'Bearer invalid'}));assert.equal(r.status,401);assert.equal(db.calls.length,0);});
test('unapproved origins fail before database or generation work',async()=>{const{createHandler}=await mod();const db=database();const r=await createHandler({db,key:'fake-secret'})(req({action:'create'},{origin:'https://untrusted.invalid'}));assert.equal(r.status,403);assert.equal(db.calls.length,0);});
test('status/output owner comes only from verified JWT, never request body',async()=>{const{createHandler}=await mod();const db=database();const r=await createHandler({db,key:'fake-secret'})(req({action:'output',requestId:rid,userId:'attacker'}));assert.equal(r.status,404);const query=db.calls.find(c=>c.table==='chisel_credit_jobs');assert.equal(query.filters.user_id,uid);assert.equal(query.filters.environment,'PRODUCTION');});
test('a tampered credit quote is refused before wallet reservation or paid request',async()=>{const{createHandler}=await mod();const db=database();const image='data:image/jpeg;base64,'+fs.readFileSync(path.join(__dirname,'fixtures/portrait-male.jpg')).toString('base64');let apiCalls=0;const r=await createHandler({db,key:'fake-secret',fetcher:()=>{apiCalls++;throw Error();}})(req({action:'create',requestId:rid,image,quality:'detail',shape:'square',look:{category:'hair',preset:'crop',color:'match'},consent:true,quotedCredits:1}));assert.equal(r.status,409);assert.equal((await r.json()).error,'confirm_credit_cost');assert.equal(apiCalls,0);assert.ok(!db.calls.some(c=>c.name==='chisel_credit_reserve'));});
test('insufficient server balance prevents all provider work even after a valid quote',async()=>{const{createHandler}=await mod();const db=database();const image='data:image/jpeg;base64,'+fs.readFileSync(path.join(__dirname,'fixtures/portrait-male.jpg')).toString('base64');let apiCalls=0;const r=await createHandler({db,key:'fake-secret',fetcher:()=>{apiCalls++;throw Error();}})(req({action:'create',requestId:rid,image,quality:'standard',shape:'square',look:{category:'hair',preset:'crop',color:'match'},consent:true,quotedCredits:1,userId:'attacker'}));assert.equal(r.status,409);assert.equal((await r.json()).error,'insufficient_credits');assert.equal(apiCalls,0);assert.equal(db.calls.find(c=>c.name==='chisel_credit_reserve').args.p_user,uid);});
