const test=require('node:test'),assert=require('node:assert/strict');const stats=require('../www/chisel-precision-stats.js'),protocol=require('../www/chisel-precision-protocol.js'),core=require('../www/chisel-precision-core.js');
function faceFrame(overrides={}){return{quality:{brightness:135,sharpness:180,fill:.52,rollDeg:.6,yawDeg:1.2,pitchDeg:1.1,expression:.04,modelConfidence:.97,occlusion:.01,glare:.02,...overrides.quality},metrics:{cheekboneWidth:.681,jawWidth:.532,gonialAngle:121.4,lipFullness:.408,eyeSpacing:1.012,canthalTilt:4.8,browArch:.071,bloatFullness:.7712,mouthOpening:.035,...overrides.metrics},skin:{lab:[62.1,11.2,17.4],lipLab:[44.2,19.8,8.4],neckLab:[55.1,10.2,16.4],redness:31,evenness:77,blemish:22,neckRedness:28,neckEvenness:75,...overrides.skin}};}
function bodyFrame(kind,n=0,overrides={}){return{quality:{brightness:140,sharpness:120,fill:.74,tiltDeg:1.1,modelConfidence:.96,maskConfidence:.94,limbVisibility:.97,occlusion:.01,...overrides.quality},metrics:kind==='front'?{shoulderWidth:.431+n*.0008,waistWidth:.296+n*.0005,hipWidth:.384+n*.0006,torsoTiltDeg:1.2+n*.05,...overrides.metrics}:{waistDepth:.205+n*.0004,hipDepth:.268+n*.0005,neckAngle:52.4+n*.08,...overrides.metrics}};}
test('modules compose',()=>{assert.equal(core.PROTOCOLS,protocol.PROTOCOLS);assert.equal(core.median,stats.median);});
test('robust consensus rejects outlier',()=>{const r=core.robustConsensus([1,1.01,.99,1.005,.995,3],{minimum:5,maxRelativeSpread:.03});assert.equal(r.valid,true);assert.equal(r.rejected,1);assert.ok(r.ci95<.02);});
test('face protocol requires seven accepted frames and 90 quality',()=>{assert.equal(core.evaluateProtocol(Array.from({length:6},()=>faceFrame()),'face').accepted,false);const r=core.evaluateProtocol(Array.from({length:7},()=>faceFrame()),'face');assert.equal(r.accepted,true);assert.ok(r.score>=90);});
test('face fusion rejects unstable bloat',()=>{const stable=Array.from({length:8},(_,i)=>faceFrame({metrics:{cheekboneWidth:.681+i*.0003,jawWidth:.532+i*.0002,bloatFullness:.7712+i*.0001}}));assert.equal(core.fuseFaceMeasurements(stable).accepted,true);const unstable=stable.map((s,i)=>({...s,metrics:{...s.metrics,bloatFullness:i%2?.69:.84}}));assert.equal(core.fuseFaceMeasurements(unstable).accepted,false);});
test('expression calibration fuses neutral and open batches',()=>{const neutral=Array.from({length:8},(_,i)=>faceFrame({metrics:{cheekboneWidth:.681+i*.0002,jawWidth:.532+i*.0002,gonialAngle:121.4+i*.03,mouthOpening:.035+i*.0002}})),opened=Array.from({length:8},(_,i)=>faceFrame({quality:{expression:.38+i*.002},metrics:{cheekboneWidth:.674+i*.0002,jawWidth:.548+i*.0002,gonialAngle:126.1+i*.04,mouthOpening:.31+i*.001}})),r=core.fuseExpressionCalibration(neutral,opened);assert.equal(r.accepted,true);assert.ok(r.corrected.jawWidth.value<r.openMetrics.jawWidth.value);});
test('skin fusion rejects colour drift',()=>{const stable=Array.from({length:8},(_,i)=>faceFrame({quality:{brightness:132+i*.4},skin:{lab:[62.1+i*.08,11.2+i*.04,17.4-i*.03],lipLab:[44.2+i*.05,19.8,8.4],neckLab:[55.1+i*.05,10.2,16.4],redness:31+i*.1,evenness:77-i*.1,blemish:22+i*.1,neckRedness:28+i*.1,neckEvenness:75-i*.1}}));assert.equal(core.fuseSkinMeasurements(stable).accepted,true);const bad=stable.map((s,i)=>({...s,skin:{...s.skin,lab:[45+i*5,4+i*2,8-i*1.5]}}));assert.equal(core.fuseSkinMeasurements(bad).accepted,false);});
test('body fusion uses front side and calibration',()=>{const front=Array.from({length:4},(_,i)=>bodyFrame('front',i)),side=Array.from({length:4},(_,i)=>bodyFrame('side',i)),base=core.fuseBodyMeasurements(front,side);assert.equal(base.accepted,true);const calibrated=core.fuseBodyMeasurements(front,side,{baselineWaistCm:78,baselinePhotoPerimeter:base.ratios.photoWaistPerimeter});assert.equal(calibrated.calibratedWaistCm,78);assert.ok(base.ratios.photoWaistPerimeterCi95>=0);});
test('tracking requires change beyond uncertainty and compatible setup',()=>{assert.equal(core.compareTrackedMetric({value:.7,ci95:.01},{value:.712,ci95:.01}).meaningful,false);assert.equal(core.compareTrackedMetric({value:.7,ci95:.005},{value:.74,ci95:.005}).meaningful,true);assert.equal(core.compatibleSetup({kind:'face',camera:'front',aspect:.75,fill:.52,brightness:135},{kind:'face',camera:'front',aspect:.76,fill:.54,brightness:142}).compatible,true);});
