const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const canonical=fs.readFileSync(path.join(root,'www/chisel-tryon-runtime-fixes.js'),'utf8');
const packaged=fs.readFileSync(path.join(root,'android/app/src/main/assets/public/chisel-tryon-runtime-fixes.js'),'utf8');
const workflow=fs.readFileSync(path.join(root,'..','.github','workflows','chisel-tests.yml'),'utf8');
const visualRunner=fs.readFileSync(path.join(root,'tests','tryon-visual-runner.mjs'),'utf8');
const api=require('../www/chisel-tryon-runtime-fixes.js');

test('V5 try-on runtime is synchronized into Android',()=>{assert.equal(packaged,canonical);assert.match(canonical,/__chiselPremiumHairV5/);assert.match(canonical,/__chiselPremiumBeardV5/);});
test('V5 removes forehead needle roots and uses a visible style-specific hair mass',()=>{assert.match(canonical,/roots start inside the existing hair mass/);assert.match(canonical,/drawStyleMass/);assert.match(canonical,/drawStyleFall/);assert.doesNotMatch(canonical,/for\(let k=0;k<46;k\+\+\)/);});
test('style summary includes makeup and is resynchronized after polish auto-collapse',()=>{assert.equal(api.previewSummary({id:'butterfly',name:'Butterfly layers'},{id:'none',name:'Clean'},{id:'peachlift',name:'Peach lift'}),'Butterfly layers + Peach lift');assert.match(canonical,/setTimeout\(syncPreviewSummary,180\)/);});
test('women cuts keep strongly distinct length, silhouette and texture profiles',()=>{const bob=api.styleVisualProfile({id:'frenchbob',fall:.5,jitter:.025},'women');const butterfly=api.styleVisualProfile({id:'butterfly',fall:1.08,jitter:.05},'women');const curls=api.styleVisualProfile({id:'curls',fall:.9,jitter:.115},'women');assert.ok(butterfly.fallPx>bob.fallPx*1.7);assert.ok(curls.textureStrength>butterfly.textureStrength*1.5);assert.notEqual(bob.silhouette,butterfly.silhouette);assert.notEqual(butterfly.silhouette,curls.silhouette);});
test('men crop, quiff and flow are separated by front lift, silhouette and length',()=>{const crop=api.styleVisualProfile({id:'crop'},'men');const quiff=api.styleVisualProfile({id:'quiff'},'men');const flow=api.styleVisualProfile({id:'mlong'},'men');assert.ok(quiff.frontLift>crop.frontLift*1.7);assert.ok(flow.fallPx>=.62);assert.notEqual(crop.silhouette,quiff.silhouette);assert.notEqual(quiff.silhouette,flow.silhouette);});
test('beard profiles create visibly progressive coverage instead of dash-like strokes',()=>{assert.equal(typeof api.beardVisualProfile,'function');const clean=api.beardVisualProfile({id:'none'}),stubble=api.beardVisualProfile({id:'stubble'}),short=api.beardVisualProfile({id:'short'}),full=api.beardVisualProfile({id:'full'});assert.equal(clean.coverage,0);assert.ok(stubble.coverage>=.18);assert.ok(short.coverage>stubble.coverage*1.45);assert.ok(full.coverage>short.coverage*1.25);assert.ok(short.hairCount>stubble.hairCount);assert.ok(full.baseOpacity>short.baseOpacity);assert.match(canonical,/soft beard mass/);assert.match(canonical,/micro follicles/);});
test('visual QA isolates beard differences using the same haircut',()=>{assert.match(visualRunner,/crop-clean/);assert.match(visualRunner,/crop-soft-stubble/);assert.match(visualRunner,/crop-short-beard/);assert.match(visualRunner,/beardsDistinct/);assert.match(visualRunner,/hairStylesDistinct/);});
test('visual try-on QA has enough time for slower female MediaPipe startup',()=>{assert.match(workflow,/tryon-visual-qa:[\s\S]*timeout-minutes:\s*4/);assert.match(workflow,/timeout --signal=TERM --kill-after=10s 150s/);assert.match(visualRunner,/const DEADLINE=120000/);});
test('fake camera generation is bounded to a small deterministic frame count',()=>{const matches=workflow.match(/-frames:v 60/g)||[];assert.ok(matches.length>=2);assert.doesNotMatch(workflow,/-t 20/);assert.doesNotMatch(workflow,/-t 25/);});
