const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const hair=read('www/chisel-tryon-hair-v5.js');
const hairPack=read('android/app/src/main/assets/public/chisel-tryon-hair-v5.js');
const beard=read('www/chisel-beard-tuning-v5.js');
const beardPack=read('android/app/src/main/assets/public/chisel-beard-tuning-v5.js');
const loader=read('www/chisel-ar-coach-core.js');
const loaderPack=read('android/app/src/main/assets/public/chisel-ar-coach-core.js');
const v4=read('www/chisel-tryon-runtime-fixes.js');
const workflow=read('../.github/workflows/chisel-tests.yml');

test('V5 try-on modules are synchronized into Android',()=>{assert.equal(hairPack,hair);assert.equal(beardPack,beard);assert.equal(loaderPack,loader);});
test('V5 hair is actually loaded after the V4 fallback',()=>{assert.match(loader,/chisel-tryon-runtime-fixes\.js/);assert.match(loader,/chisel-tryon-hair-v5\.js/);assert.match(loader,/ChiselTryonHairV5\.install/);assert.match(hair,/drawHair\.__v5=true/);});
test('men hair silhouettes have strong geometry separation',()=>{assert.match(hair,/buzz:\[\.05,0,\.90\]/);assert.match(hair,/crop:\[\.11,0,\.96\]/);assert.match(hair,/quiff:\[\.34,0,1\.04\]/);assert.match(hair,/mlong:\[\.22,\.68,1\.08\]/);assert.match(hair,/s\.id==='crop'/);});
test('women hair lengths and widths are visibly separated',()=>{assert.match(hair,/frenchbob:\[\.20,\.48,1\.08\]/);assert.match(hair,/butterfly:\[\.31,1\.08,1\.15\]/);assert.match(hair,/curls:\[\.35,\.90,1\.20\]/);assert.match(hair,/coils:\[\.38,\.82,1\.24\]/);});
test('beard tuning makes stubble short and full progressively stronger while shortening dash length',()=>{assert.match(beard,/stubble:\[\.13,\.40,260,\.0022\]/);assert.match(beard,/short:\[\.24,\.46,430,\.0036\]/);assert.match(beard,/full:\[\.34,\.52,620,\.0055\]/);assert.match(beard,/drawBeard\.__v5=true/);assert.match(loader,/chisel-beard-tuning-v5\.js/);assert.match(loader,/ChiselBeardTuningV5\.install/);});
test('V4 state sync and clean beard default remain available underneath V5',()=>{assert.match(v4,/setTimeout\(syncPreviewSummary,180\)/);assert.match(v4,/styleBeard=0/);});
test('fake camera generation remains bounded',()=>{const matches=workflow.match(/-frames:v 60/g)||[];assert.ok(matches.length>=2);});
