const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const hair=read('www/chisel-tryon-hair-v5.js');
const hairPack=read('android/app/src/main/assets/public/chisel-tryon-hair-v5.js');
const beard=read('www/chisel-beard-tuning-v5.js');
const beardPack=read('android/app/src/main/assets/public/chisel-beard-tuning-v5.js');
const loader=read('www/chisel-ar-coach-core.js');
const loaderPack=read('android/app/src/main/assets/public/chisel-ar-coach-core.js');
const v4=read('www/chisel-tryon-runtime-fixes.js');
const workflow=read('../.github/workflows/chisel-tests.yml');
const visual=read('tests/tryon-visual-runner.mjs');
const hairApi=require('../www/chisel-tryon-hair-v5.js');
const beardApi=require('../www/chisel-beard-tuning-v5.js');

test('V6 try-on modules are synchronized into Android while keeping loader compatibility',()=>{assert.equal(hairPack,hair);assert.equal(beardPack,beard);assert.equal(loaderPack,loader);assert.match(loader,/chisel-tryon-hair-v5\.js/);assert.match(loader,/chisel-beard-tuning-v5\.js/);});
test('V6 hair replaces one generic contour with semantic silhouette families',()=>{assert.match(hair,/renderer\.__v6=true/);assert.match(hair,/function drawFamily/);assert.doesNotMatch(hair,/const outer=roots\.map/);assert.equal(hairApi.styleBlueprint('buzz').family,'clipper');assert.equal(hairApi.styleBlueprint('crop').family,'fringe-crop');assert.equal(hairApi.styleBlueprint('quiff').family,'swept-peak');assert.equal(hairApi.styleBlueprint('mlong').family,'flow');});
test('men haircuts are qualitatively different, not just small parameter changes',()=>{const buzz=hairApi.styleBlueprint('buzz'),crop=hairApi.styleBlueprint('crop'),quiff=hairApi.styleBlueprint('quiff'),flow=hairApi.styleBlueprint('mlong');assert.equal(new Set([buzz.family,crop.family,quiff.family,flow.family]).size,4);assert.ok(quiff.crown>crop.crown*2);assert.ok(flow.length>.5);});
test('women styles use distinct construction families',()=>{const ids=['frenchbob','butterfly','curtain','curls','coils','shag','braids','pony','bun','updo'];const families=ids.map(id=>hairApi.styleBlueprint(id).family);assert.ok(new Set(families).size>=9);assert.equal(hairApi.styleBlueprint('frenchbob').family,'bob');assert.equal(hairApi.styleBlueprint('butterfly').family,'long-layers');assert.equal(hairApi.styleBlueprint('curtain').family,'curtain');assert.equal(hairApi.styleBlueprint('curls').family,'curl-mass');assert.equal(hairApi.styleBlueprint('coils').family,'coil-mass');});
test('V6 beard has visibly separated coverage maps',()=>{assert.match(beard,/renderer\.__v6=true/);const clean=beardApi.beardBlueprint('none'),stubble=beardApi.beardBlueprint('stubble'),short=beardApi.beardBlueprint('short'),goatee=beardApi.beardBlueprint('goatee'),mous=beardApi.beardBlueprint('mous');assert.equal(clean.jaw,0);assert.ok(short.jaw>stubble.jaw);assert.ok(short.cheeks>stubble.cheeks);assert.equal(goatee.cheeks,0);assert.equal(mous.cheeks,0);assert.equal(mous.chin,0);assert.equal(mous.moustache,1);});
test('visual QA still isolates haircut and beard differences',()=>{assert.match(visual,/crop-clean/);assert.match(visual,/crop-soft-stubble/);assert.match(visual,/crop-short-beard/);assert.match(visual,/hairStylesDistinct/);assert.match(visual,/beardsDistinct/);});
test('V4 state sync and clean beard default remain underneath V6',()=>{assert.match(v4,/setTimeout\(syncPreviewSummary,180\)/);assert.match(v4,/styleBeard=0/);});
test('fake camera generation remains bounded',()=>{const capped=workflow.match(/-frames:v 16/g)||[];const timed=workflow.match(/timeout --signal=TERM --kill-after=5s 20s\s+\\\s*\n\s*ffmpeg/g)||[];assert.ok(capped.length>=2);assert.ok(timed.length>=4);assert.doesNotMatch(workflow,/-frames:v 60/);});